//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaPaciente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int ID_Paciente { get; set; }
        public string Nombre_Paciente { get; set; }
        public string Apellido_Paciente { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string Tipo_Documento { get; set; }
        public string Numero_Documento { get; set; }
        public string Sexo_Paciente { get; set; }
        public string Direccion_Paciente { get; set; }
        public string Ciudad_Residencia { get; set; }
        public string Correo_Paciente { get; set; }
        public string Telefono_Paciente { get; set; }
    }
}
